version: "3.8"

services:
  frontend:
    build:
      context: ./client
    container_name: vite_frontend
    networks:
      - web

  backend:
    build:
      context: ./  # Root of the project
      dockerfile: ./server/Dockerfile  # Path to the Dockerfile inside server/
    container_name: fastapi_backend
    networks:
      - web

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"  # Only expose Nginx to the host
    networks:
      - web
    depends_on:
      - frontend
      - backend

    environment:
      - client_max_body_size=50M

networks:
  web:
    driver: bridge

